CREATE TYPE "CHECKIN_MODE" AS ENUM ('ATTENDEE_CREDENTIAL', 'BOARD_QR');
CREATE TYPE "EVENT_QR_BEHAVIOR" AS ENUM ('JOIN_ONLY', 'JOIN_AND_CHECKIN');

ALTER TABLE "events"
ADD COLUMN "checkinModes" "CHECKIN_MODE"[] NOT NULL DEFAULT ARRAY['ATTENDEE_CREDENTIAL', 'BOARD_QR']::"CHECKIN_MODE"[],
ADD COLUMN "eventQrBehavior" "EVENT_QR_BEHAVIOR" NOT NULL DEFAULT 'JOIN_ONLY';
