CREATE TYPE "USER_ROLE_NEW" AS ENUM ('USER', 'ADMIN');

ALTER TABLE "users" ALTER COLUMN "role" DROP DEFAULT;

ALTER TABLE "users"
ALTER COLUMN "role" TYPE "USER_ROLE_NEW"
USING (
  CASE
    WHEN "role" = 'ADMIN'::"USER_ROLE" THEN 'ADMIN'::"USER_ROLE_NEW"
    ELSE 'USER'::"USER_ROLE_NEW"
  END
);

ALTER TYPE "USER_ROLE" RENAME TO "USER_ROLE_OLD";
ALTER TYPE "USER_ROLE_NEW" RENAME TO "USER_ROLE";
DROP TYPE "USER_ROLE_OLD";

ALTER TABLE "users" ALTER COLUMN "role" SET DEFAULT 'USER';

ALTER TABLE "events"
ADD COLUMN "allowedDomains" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "allowedEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "blockedEmails" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
